# .github/workflows/release.yaml

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  release-linux-amd64:
    name: Build release for TCG4
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: arm
        binary_name: sensor
        project_path: ./cmd/sensor
        extra_files: LICENSE README.md
        ldflags: -X 'main.AppVersion=${{ github.ref_name }}'